// AUTO-GENERATED by scripts/gen-engine-version.cjs (npm prebuild). Do not edit by hand.
// P-UX-21: LF-normalized content-hash of the number-engine file set; folded into
// computeAdvisoryHash so engine changes invalidate stale advisory caches.
export const ENGINE_VERSION = '53ec6cd11605'
